### ISSUE TITLE
App crashes after entering stationary region on Android

### ISSUE THREAD

**Issue by projectpublius** [mauron85/react-native-background-geolocation#320] opened 2018-11-13 17:39 UTC
## Your Environment

* Plugin version: 0.5.0-alpha.47
* Platform: Android
* OS version: 9
* Device manufacturer and model: 

* Running in Simulator: No
* React Native version: 0.57.5
* Plugin configuration options: 
      desiredAccuracy: BackgroundGeolocation.HIGH_ACCURACY,
      stationaryRadius: 5,
      distanceFilter: 1,
      startOnForeground: true,
      notificationTitle: "Background tracking",
      notificationText: "enabled",
      debug: false,
      startOnBoot: false,
      stopOnTerminate: true,
      locationProvider: BackgroundGeolocation.DISTANCE_FILTER_PROVIDER,
      interval: 10000,
      fastestInterval: 1000,
      activitiesInterval: 10000,
      stopOnStillActivity: false,
      activityType: "AutomotiveNavigation"
* Link to your project:

## Context

After launching the location service, the app crashes upon entering stationary region.  The location service reports a "New stationary BGLocation[...]" and then crashes with "java.lang.StringIndexOutOfBoundsException: String index out of range: -2"

## Steps to Reproduce

1. Start service and leave device stationary with app in foreground

## Debug logs

java.lang.StringIndexOutOfBoundsException: String index out of range: -2
at java.lang.String.substring(String.java:2036)
        at android.support.v4.content.FileProvider$SimplePathStrategy.getFileForUri(FileProvider.java:735)
        at android.support.v4.content.FileProvider.query(FileProvider.java:436)
        at android.content.ContentProvider.query(ContentProvider.java:1055)
        at android.content.ContentProvider.query(ContentProvider.java:1147)
        at android.content.ContentProvider$Transport.query(ContentProvider.java:240)
        at android.content.ContentResolver.query(ContentResolver.java:802)
        at android.content.ContentResolver.query(ContentResolver.java:752)
        at android.content.ContentResolver.query(ContentResolver.java:710)
        at com.marianhello.bgloc.data.provider.ContentProviderLocationDAO.getLocationsCount(ContentProviderLocationDAO.java:112)
        at com.marianhello.bgloc.data.provider.ContentProviderLocationDAO.persistLocation(ContentProviderLocationDAO.java:286)
        at com.marianhello.bgloc.data.provider.ContentProviderLocationDAO.persistLocationForSync(ContentProviderLocationDAO.java:335)
        at com.marianhello.bgloc.LocationService$PostLocationTask$1.run(LocationService.java:594)

**Comment by projectpublius** [comment] 2018-11-13 17:45
Fixable by reverting to 0.5.0-alpha.45.

**Comment by mauron85** [comment] 2018-11-14 09:02
Unfortunately cannot reproduce on Oreo. Will try later on Pie emulator.

**Comment by mauron85** [comment] 2018-11-14 09:22
What I really don't understand from your logs is why ContentResolver resolved FileProvider to do the query and not the plugin's [LocationContentProvider](https://github.com/mauron85/background-geolocation-android/blob/master/src/main/java/com/marianhello/bgloc/data/provider/LocationContentProvider.java).

Can you try to reinstall the app? Can you reproduce on newly created app, with just this plugin?

**Comment by projectpublius** [comment] 2018-11-14 18:55
The issue persisted after running ./gradlew clean.  I also tested on another physical device running Android 7 and experienced the same issue.

But when I created a new app with just this plugin, the app didn't crash.

I then started removing plugins one by one from the original app, and when I removed the `rn-fetch-blob` plugin (https://github.com/joltup/rn-fetch-blob), the app stopped crashing.

**Comment by mauron85** [comment] 2018-11-14 22:31
So in other words there not compatible. Fortunately this plugin is more configurable, so you can override it's `android:authorities` here `https://github.com/mauron85/background-geolocation-android/blob/master/build.gradle#L69`.

On filesystem it should reside somewhere in `node_modules` `common` `build.gradle` (sorry don't throw the exact path from memory on you). The ugly side is that this will be reverted with every package upgrade.

**Comment by mauron85** [comment] 2018-11-20 09:39
FYI: fixed in 0.5.0-alpha.48

**Closed** 2018-11-20 09:39 UTC
Labels: enhancement, inprogress
