### ISSUE TITLE
Android build failure 

### ISSUE THREAD

**Issue by iamchathu** [mauron85/react-native-background-geolocation#304] opened 2018-10-11 08:50 UTC
## Your Environment

* Plugin version: ^0.5.0-alpha.42
* Platform: Android
* OS version: MacOS Mojave 10.14
* Device manufacturer and model: Apple MacBook Pro
* React Native version: 0.57.2
* Plugin configuration options: Default
* Link to your project:

## Expected Behavior

I tried to build release APK of the project for Android

## Actual Behavior

It should build Android Release APK.

## Steps to Reproduce

1. `react-native init NewProject`
2. `yarn add react-native-mauron85-background-geolocation`
3. Add default code.
4. run `cd android && ./gradlew assembleRelease`

## Debug logs

```
$ cd android && ./gradlew assembleRelease

> Configure project :app
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html

> Configure project :react-native-device-info
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html

> Configure project :react-native-mauron85-background-geolocation
WARNING: Configuration 'releaseCompile' is obsolete and has been replaced with 'releaseImplementation' and 'releaseApi'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
WARNING: Configuration 'debugCompile' is obsolete and has been replaced with 'debugImplementation' and 'debugApi'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
WARNING: Configuration 'testCompile' is obsolete and has been replaced with 'testImplementation' and 'testApi'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
WARNING: Configuration 'testApi' is obsolete and has been replaced with 'testImplementation'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
WARNING: Configuration 'androidTestCompile' is obsolete and has been replaced with 'androidTestImplementation' and 'androidTestApi'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
WARNING: Configuration 'androidTestApi' is obsolete and has been replaced with 'androidTestImplementation'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html

> Configure project :react-native-mauron85-background-geolocation-common
publishNonDefault is deprecated and has no effect anymore. All variants are now published.
WARNING: Configuration 'androidTestCompile' is obsolete and has been replaced with 'androidTestImplementation' and 'androidTestApi'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
WARNING: Configuration 'androidTestApi' is obsolete and has been replaced with 'androidTestImplementation'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
WARNING: Configuration 'testCompile' is obsolete and has been replaced with 'testImplementation' and 'testApi'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
WARNING: Configuration 'testApi' is obsolete and has been replaced with 'testImplementation'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
WARNING: Configuration 'oreoCompile' is obsolete and has been replaced with 'oreoImplementation' and 'oreoApi'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html


FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:preReleaseBuild'.
> Could not resolve all task dependencies for configuration ':app:releaseRuntimeClasspath'.
   > Could not resolve project :react-native-mauron85-background-geolocation-common.
     Required by:
         project :app > project :react-native-mauron85-background-geolocation
      > Project :react-native-mauron85-background-geolocation declares a dependency from configuration 'releaseCompile' to configuration 'preoreoRelease' which is not declared in the descriptor for project :react-native-mauron85-background-geolocation-common.
```

**Comment by mauron85** [comment] 2018-10-23 14:55
Try to enable gradl3 support

https://github.com/mauron85/react-native-background-geolocation#experimental-gradle-3-support

**Comment by anthonyhumphreys** [comment] 2018-10-28 12:05
I've been fighting an issue on this too, my error was that the task assembleDebug could not be created for -common as a task with that name already exists. Any ideas?

**Comment by mauron85** [comment] 2018-10-28 12:08
If you're using latest react-native 57, they upgraded to gradle 4, which is using different semantics.
You have to put option gradle3EXPERIMENTAL to your build.gradle (instruction are in readme) to enable building with gradle4.

However I'll publish soon version, where this flag will be not necessary.

**Comment by anthonyhumphreys** [comment] 2018-10-29 09:21
Okay, i've added gradle3EXPERIMENTAL as per the instructions, still getting that error though - does the build task need namespacing or something? Sorry, I'm not totally au fait with gradle

**Comment by mauron85** [comment] 2018-10-29 09:34
Plugin was updated yesterday. There should be no need to add gradle3EXPERIMENTAL when using ReactNative v57. But if your project was created with older react native you will need to upgrade (instructions on rn site) or start fresh:

1. react-native init NewProject
2. cd newProject
3. yarn add react-native-mauron85-background-geolocation
3. react-native link react-native-mauron85-background-geolocation
4. add code
5. react-native run-android

Just tested all above. Working fine.

**Comment by anthonyhumphreys** [comment] 2018-10-29 09:35
Awesome, thanks! Will give it a go.

**Comment by anthonyhumphreys** [comment] 2018-10-29 09:39
```
> Configure project :react-native-mauron85-background-geolocation-common
Enabling gradle3EXPERIMENTAL support for gradle Gradle 4.10.1
publishNonDefault is deprecated and has no effect anymore. All variants are now published.
WARNING: The specified Android SDK Build Tools version (27.0.3) is ignored, as it is below the minimum supported version (28.0.3) for Android Gradle Plugin 3.4.0-alpha02.
Android SDK Build Tools 28.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '27.0.3'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':react-native-mauron85-background-geolocation-common'.
> Cannot add task 'assembleDebug' as a task with that name already exists.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html
```

Still getting the assembleDebug issue :( Any ideas?

```
react-native-cli: 2.0.1
react-native: 0.57.3
```

Thanks for all your help btw!

**Comment by mauron85** [comment] 2018-10-29 10:13
>Cannot add task 'assembleDebug' as a task with that name already exists.

Hmm. I cannot reproduce this one. My skeleton project is using gradle 4.4. Yours for some reason 4.10. And we're using same react-native-cli.

**Comment by anthonyhumphreys** [comment] 2018-10-29 10:20
Not sure about the Gradle discrepancy...however, I can confirm its not compiling. This was what was missing from my root build.gradle:

```
task wrapper(type: Wrapper) {
    gradleVersion = '4.4' // again not sure what's going on here *shrug*
    distributionUrl = distributionUrl.replace("bin", "all")
}
```

Now i have an issue with FBSDK....love me some android build issues haha. Cheers bud! I think this can probably be closed :)

**Comment by anthonyhumphreys** [comment] 2018-10-29 10:30
Yeah its compiling fine except the fbsdk. Unless OP replies i think its safe to close :)

**Comment by mauron85** [comment] 2018-10-29 10:30
Ok. Understood. Closing. Reopen or raise new issue if needed.

**Closed by mauron85** 2018-10-29 10:30 UTC
