### ISSUE TITLE
Location data not Providing Bearing data on Android

### ISSUE THREAD

**Issue by nahidmbstu** [mauron85/react-native-background-geolocation#229] opened 2018-07-08 08:38 UTC
## Your Environment

Environment:
  OS: Linux 4.15
  Node: 8.11.3
  Yarn: Not Found
  npm: 5.6.0
  Watchman: 4.7.0

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4
 "react-native-mauron85-background-geolocation": "^0.5.0-alpha.34",

## Context

    BackgroundGeolocation.configure({
    desiredAccuracy: BackgroundGeolocation.HIGH_ACCURACY,
    stationaryRadius: 50,
    distanceFilter: 50,
    notificationTitle: "Background tracking",
    notificationText: "enabled",
    debug: true,
    startOnBoot: false,
    stopOnTerminate: false,
    locationProvider: BackgroundGeolocation.ACTIVITY_PROVIDER,
    interval: 10000,
    fastestInterval: 5000,
    activitiesInterval: 10000,
    stopOnStillActivity: false
  });

    BackgroundGeolocation.on("location", location => {
      this.setState({
        current_loc_long: location.longitude,
        current_loc_lat: location.latitude
      });

      console.log("[DEBUG] BackgroundGeolocation location", location);

```
accuracy
:
16.506999969482422
altitude
:
-28.5
isFromMockProvider
:
false
latitude
:
23.7720361
locationProvider
:
1
longitude
:
90.3599058
mockLocationsEnabled
:
false
provider
:
"fused"
time
:
1531039039337

```

**Comment by mauron85** [comment] 2018-07-09 09:40
I think this is duplicate of https://github.com/mauron85/react-native-background-geolocation/issues/218
Closing. Please continue discussion on above link.

**Closed by mauron85** 2018-07-09 09:40 UTC
