### ISSUE TITLE
Speed and Heading

### ISSUE THREAD

**Issue by kenobi91** [mauron85/react-native-background-geolocation#291] opened 2018-09-30 08:45 UTC
Is there any way to get speed and heading information ?

**Comment by NULL-SWEAT** [comment] 2018-10-18 00:46
+1
I'm not getting speed as well.
Using the ACTIVITY_PROVIDER

When using the react-native-fused-location lib, the location object contains the speed.

**Comment by plblueraven** [comment] 2018-10-29 15:56
Duplicate of #282

**Comment by mauron85** [comment] 2018-11-13 20:37
Some providers just don't provide speed. Eg. it doesn't make sense for network provider or wifi provider.

**Comment by mauron85** [comment] 2018-11-13 20:37
Closing as duplicate.

**Closed by mauron85** 2018-11-13 20:37 UTC
Labels: duplicate

**Comment by xgenem** [comment] 2022-09-13 10:12
Sorry for re-opening. How about the heading value?
