### ISSUE TITLE
IOS Build Issue, duplicate RCTBridge

### ISSUE THREAD

**Issue by UrbanSam** [mauron85/react-native-background-geolocation#44] opened 2017-03-02 06:44 UTC
## Your Environment

* Plugin version: 0.2.0-alpha.6
* Platform: iOS 
* OS version: Mac OS X El Capitan
* React Native version: 0.41.2

## Context

Having issue build with IOS, in Xcode 8.

## Possible Fix

Seem to fix with removal of import RCTBridge.h in RCTBackgroundGeolocation.m

#if __has_include("RCTBridge.h")    **

**Comment by dorthwein** [comment] 2017-03-19 21:24
same issue - any solutions?

**Comment by UrbanSam** [comment] 2017-03-20 03:00
@dorthwein  Was the possible fix helps?

**Comment by dorthwein** [comment] 2017-03-20 14:53
@UrbanSam negative ghost ride - no luck.  It ended up causing several other bugs/things not loading. 

Honestly, I went with another package.  I'd prefer to use this one as there isn't a license fee for android, but such is life.

**Comment by UrbanSam** [comment] 2017-03-20 17:26
@dorthwein What others bug came up? And which RN were you on?
Here's a example of lines to remove.

#if __has_include("RCTBridge.h")    <!--- remove this
#import "RCTBridge.h"                   <!--- remove this
#else                                               <!--- remove this
#import <React/RCTBridge.h>
#endif                                             <!--- remove this

**Comment by mauron85** [comment] 2017-03-20 17:35
@UrbanSam this brings me just tears, as your changes is actually reverting what I did in last commit. What version is your RN lib?

**Comment by UrbanSam** [comment] 2017-03-20 17:37
@mauron85 0.41.2

**Comment by mauron85** [comment] 2017-03-20 17:39
Can you test on a clean project? Maybe you have duplicate files left by upgrade mechanism or something...
Or at least remove/reinstall react-native module.

**Comment by UrbanSam** [comment] 2017-03-20 18:07
I tried with new project with RN 0.41.2, it still the same issue.

Here's the result you need, I use sublime to find in folder node_module
[searchResult.txt](https://github.com/mauron85/react-native-background-geolocation/files/855921/searchResult.txt)

**Comment by UrbanSam** [comment] 2017-03-20 18:16
Hi, by switching the if statement to check <React/RCTBrdige.h> instead, seem to able to fix it as well.
I'm able to build with this line below

#if __has_include(<React/RCTBridge.h>)
#import <React/RCTBridge.h>
#else
#import "RCTBridge.h"
#endif

**Comment by mauron85** [comment] 2017-03-20 18:21
Sorry can u post result of find not grep. (I've updated instructions)

**Comment by UrbanSam** [comment] 2017-03-20 18:24
node_modules//react-native/React/Base/RCTBridge+Private.h
node_modules//react-native/React/Base/RCTBridge.h
node_modules//react-native/React/Base/RCTBridge.m
node_modules//react-native/React/Base/RCTBridgeDelegate.h
node_modules//react-native/React/Base/RCTBridgeMethod.h
node_modules//react-native/React/Base/RCTBridgeModule.h

**Comment by mauron85** [comment] 2017-03-20 18:25
That is kind of interesting. Trying to figure out where is the catch.

"RCTBridge.h" is old path pre RN 0.40
<React/RCTBridge.h> is  new path RN 0.40 and newer

**Comment by mauron85** [comment] 2017-03-20 18:45
Doesn't make sense for me at all (as I'm not macro expert), but microsoft guys did same thing as you @UrbanSam.

https://github.com/Microsoft/react-native-code-push/pull/678/files#diff-44a84efa8cad867f5ca85f13ab8c5abd

**Comment by mauron85** [comment] 2017-03-20 18:46
@UrbanSam can you make PR? Will appreciate.

**Comment by UrbanSam** [comment] 2017-03-20 19:09
@mauron85 I have made a PR in branch next

**Comment by ilyadoroshin** [comment] 2017-03-21 10:27
having the same issue.. "Duplicate interface definition for class 'RCTBridge'"

```
$ find node_modules/ -name RCTBridge*: 
node_modules/react-native/React/Base/RCTBridge+Private.h
node_modules/react-native/React/Base/RCTBridge.h
node_modules/react-native/React/Base/RCTBridge.m
node_modules/react-native/React/Base/RCTBridgeDelegate.h
node_modules/react-native/React/Base/RCTBridgeMethod.h
node_modules/react-native/React/Base/RCTBridgeModule.h
node_modules/react-native-barcode-builder/Example/ios/build/Build/Intermediates/React.build/Debug-iphonesimulator/React.build/Objects-normal/x86_64/RCTBridge.d
node_modules/react-native-barcode-builder/Example/ios/build/Build/Intermediates/React.build/Debug-iphonesimulator/React.build/Objects-normal/x86_64/RCTBridge.dia
node_modules/react-native-barcode-builder/Example/ios/build/Build/Intermediates/React.build/Debug-iphonesimulator/React.build/Objects-normal/x86_64/RCTBridge.o
node_modules/react-native-barcode-builder/Example/ios/build/Build/Intermediates/React.build/Debug-iphonesimulator/React.build/StaticAnalyzer/React/React/normal/x86_64/RCTBridge.d
node_modules/react-native-barcode-builder/Example/ios/build/Build/Intermediates/React.build/Debug-iphonesimulator/React.build/StaticAnalyzer/React/React/normal/x86_64/RCTBridge.plist
node_modules/react-native-global-props/ios/build/Build/Intermediates/React.build/Debug-iphonesimulator/React.build/Objects-normal/x86_64/RCTBridge.d
node_modules/react-native-global-props/ios/build/Build/Intermediates/React.build/Debug-iphonesimulator/React.build/Objects-normal/x86_64/RCTBridge.dia
node_modules/react-native-global-props/ios/build/Build/Intermediates/React.build/Debug-iphonesimulator/React.build/Objects-normal/x86_64/RCTBridge.o
node_modules/react-native-global-props/ios/build/Build/Intermediates/React.build/Debug-iphonesimulator/React.build/StaticAnalyzer/React/React/normal/x86_64/RCTBridge.d
node_modules/react-native-global-props/ios/build/Build/Intermediates/React.build/Debug-iphonesimulator/React.build/StaticAnalyzer/React/React/normal/x86_64/RCTBridge.plist

```
Removing the following from RCTBackgroundGeolocation.m fixes it for me: 
```
#if __has_include("RCTBridge.h")
#import "RCTBridge.h"
#else
#import <React/RCTBridge.h>
#endif

```

any thoughts?

**Comment by ilyadoroshin** [comment] 2017-03-21 10:31
looks like RCTBridge is already imported in RN 0.40 in RCTEventDispatcher.h..

**Comment by mauron85** [comment] 2017-03-21 10:35
@ilyadoroshin nice, that is indeed the root of all problems. They don't any `#ifndef` guard. 

we probably should report this to react-native team (I guess).

But they IMO should.

**Comment by mauron85** [comment] 2017-03-21 10:39
The only question in mind left is, how come change of ordering like done @UrbanSam solved this issue too.

**Comment by ilyadoroshin** [comment] 2017-03-21 10:45
@mauron85 it's all some deep-deep black magic for me, since I'm just js-developer :) wandering in the dark, removing this and that, and somehow it works.. no time to dig deeper. Tell me if you need any help to reproduce or any other data. 

And thanks a bunch for such a brilliant package! 👍

**Comment by UrbanSam** [comment] 2017-03-21 11:00
@mauron85 hmm i'm not really sure about this as well, I'm just like @ilyadoroshin say. 
But I assume it check for the path of the file exist, assuming Pre RN 0.40 would not have the file path to <React/RCTBrdige.h>, so it would make sense to import "RCTBridge.h", else import it as <React/RCTBrdige.h>.

**Comment by mauron85** [comment] 2017-03-21 13:58
Should be fixed in alpha.7. Feel free to reopen if issue still persists.

**Closed by mauron85** 2017-03-21 13:58 UTC
